name       : python-gobject
version    : 3.36.1
release    : 17
source     :
    - https://download.gnome.org/sources/pygobject/3.36/pygobject-3.36.1.tar.xz : d1bf42802d1cec113b5adaa0e7bf7f3745b44521dc2163588d276d5cd61d718f
homepage   : https://live.gnome.org/PyGObject
license    : GPL-2.0-only
summary    : Python GObject bindings
description: |
    PyGObject provides Python 2 bindings to the GObject class from GLib.
component  : programming.python
builddeps  :
    - pkgconfig(cairo-gobject)
    - pkgconfig(gobject-introspection-1.0)
    - pkgconfig(pycairo)
    - pkgconfig(python-2.7)
setup      : |
    %meson_configure -Dpython=python2
build      : |
    %ninja_build
install    : |
    %ninja_install
