name       : python-gobject
version    : 3.26.1
release    : 10
source     :
    - https://download.gnome.org/sources/pygobject/3.26/pygobject-3.26.1.tar.xz : f5577b9b9c70cabb9a60d81b855d488b767c66f867432e7fb64aa7269b04d1a9
homepage   : https://live.gnome.org/PyGObject
license    : GPL-2.0
summary    : Python GObject bindings
description: |
    PyGObject provides Python 2 bindings to the GObject class from GLib.
component  : programming.python
builddeps  :
    - pkgconfig(cairo-gobject)
    - pkgconfig(gobject-introspection-1.0)
    - pkgconfig(pycairo)
    - pkgconfig(python-2.7)
setup      : |
    %configure --disable-static --with-python=/usr/bin/python2
build      : |
    %make
install    : |
    %make_install
