name       : python-gobject
version    : 3.32.0
release    : 12
source     :
    - https://download.gnome.org/sources/pygobject/3.32/pygobject-3.32.0.tar.xz : 83f4d7e59fde6bc6b0d39c5e5208574802f759bc525a4cb8e7265dfcba45ef29
homepage   : https://live.gnome.org/PyGObject
license    : GPL-2.0-only
summary    : Python GObject bindings
description: |
    PyGObject provides Python 2 bindings to the GObject class from GLib.
component  : programming.python
builddeps  :
    - pkgconfig(cairo-gobject)
    - pkgconfig(gobject-introspection-1.0)
    - pkgconfig(pycairo)
    - pkgconfig(python-2.7)
setup      : |
    %meson_configure -Dpython=python2
build      : |
    %ninja_build
install    : |
    %ninja_install
