name       : python-gobject
version    : 3.28.2
release    : 11
source     :
    - https://download.gnome.org/sources/pygobject/3.28/pygobject-3.28.2.tar.xz : ac443afd14fcb9ff5744b65d6e2b380e70510278404fb8684a9b9fb089e6f2ca
homepage   : https://live.gnome.org/PyGObject
license    : GPL-2.0-only
summary    : Python GObject bindings
description: |
    PyGObject provides Python 2 bindings to the GObject class from GLib.
component  : programming.python
builddeps  :
    - pkgconfig(cairo-gobject)
    - pkgconfig(gobject-introspection-1.0)
    - pkgconfig(pycairo)
    - pkgconfig(python-2.7)
setup      : |
    %configure --disable-static --with-python=/usr/bin/python2
build      : |
    %make
install    : |
    %make_install
