name       : python-gobject
version    : 3.36.1
release    : 21
source     :
    - https://download.gnome.org/sources/pygobject/3.36/pygobject-3.36.1.tar.xz : d1bf42802d1cec113b5adaa0e7bf7f3745b44521dc2163588d276d5cd61d718f
homepage   : https://live.gnome.org/PyGObject
license    : LGPL-2.1-or-later
summary    : Python GObject bindings
description: |
    PyGObject provides Python bindings to the GObject class from GLib.
component  : programming.python
replaces   :
    - python3-gobject
    - devel : python3-gobject-devel
builddeps  :
    - pkgconfig(gobject-introspection-1.0)
    - pkgconfig(py3cairo)
    - pkgconfig(pycairo)
    - pkgconfig(python-2.7)
    - pkgconfig(python3)
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
