name        : python-gobject
version     : 3.18.2
release     : 5
source      :
    - http://ftp.acc.umu.se/pub/gnome/sources/pygobject/3.18/pygobject-3.18.2.tar.xz : 2a3cad1517916b74e131e6002c3824361aee0671ffb0d55ded119477fc1c2c5f
homepage    : https://live.gnome.org/PyGObject
license     : GPL-2.0
summary     : Python GObject bindings
description : |
    PyGObject provides Python 2 bindings to the GObject class from GLib.
builddeps   :
    - pkgconfig(cairo-gobject)
    - pkgconfig(gobject-introspection-1.0)
    - pkgconfig(pycairo)
    - pkgconfig(python-2.7)
setup      : |
    %configure --disable-static --with-python=/usr/bin/python2
build      : |
    %make
install    : |
    %make_install
