name       : python-gobject
version    : 3.26.0
release    : 9
source     :
    - https://download.gnome.org/sources/pygobject/3.26/pygobject-3.26.0.tar.xz : 7411acd600c8cb6f00d2125afa23303f2104e59b83e0a4963288dbecc3b029fa
homepage   : https://live.gnome.org/PyGObject
license    : GPL-2.0
summary    : Python GObject bindings
description: |
    PyGObject provides Python 2 bindings to the GObject class from GLib.
component  : programming.python
builddeps  :
    - pkgconfig(cairo-gobject)
    - pkgconfig(gobject-introspection-1.0)
    - pkgconfig(pycairo)
    - pkgconfig(python-2.7)
setup      : |
    %configure --disable-static --with-python=/usr/bin/python2
build      : |
    %make
install    : |
    %make_install
